colours:
  primary: orange-2
  secondary: green-1
  tertiary: alt-blue-1

ordering:
  - startup
  - node
  - mentors

  - partner
  - sponsor
  - supporter

  - basic
  - alumni
  - accreditor
  
  - trainer
  - registered-trainer
  - speaker
