colours:
  primary: red
  secondary: green-1
  tertiary: blue-2

ordering:
  - startup
  - node
  - mentors

  - partner
  - sponsor
  - supporter

  - basic
  - alumni
  - accreditor

  - trainer
  - registered-trainer
  - speaker
